name: stan311
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=2.305=openblas
  - blas-devel=3.11.0=5_h11c0a38_openblas
  - bottleneck=1.4.2=py311h03d0aa3_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cctools_impl_osx-arm64=1030.6.3=llvm19_1_h8c76c84_3
  - cctools_osx-arm64=1030.6.3=llvm19_1_h6d92914_3
  - clang=19.1.7=default_hf9bcbb7_7
  - clang-19=19.1.7=default_hf3020a7_7
  - clang_impl_osx-arm64=19.1.7=default_hc11f16d_7
  - clang_osx-arm64=19.1.7=h75f8d18_30
  - clangxx=19.1.7=default_hc995acf_7
  - clangxx_impl_osx-arm64=19.1.7=default_hc11f16d_7
  - clangxx_osx-arm64=19.1.7=h75f8d18_30
  - cmdstan=2.38.0=ha5c09bf_0
  - cmdstanpy=1.3.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - compiler-rt=19.1.7=h855ad52_1
  - compiler-rt_osx-arm64=19.1.7=he32a8d3_1
  - debugpy=1.8.16=py311h50f4ffc_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h50f4ffc_4
  - icu=73.2=hc8870d7_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - ld64=956.6=llvm19_1_he86490a_3
  - ld64_osx-arm64=956.6=llvm19_1_h6922315_3
  - libblas=3.11.0=5_h51639a9_openblas
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libclang-cpp19.1=19.1.7=default_hf3020a7_7
  - libcxx=20.1.8=hd7fd590_1
  - libcxx-devel=19.1.7=h6dc3340_2
  - libcxx-headers=19.1.7=h707e725_2
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libhwloc=2.12.1=default_h88f92a7_1000
  - libiconv=1.18=h23cfdf5_2
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblapacke=3.11.0=5_h1b118fd_openblas
  - libllvm19=19.1.7=hc4b4ae8_1
  - libopenblas=0.3.30=openmp_ha158390_3
  - libsigtool=0.1.3=h98dc951_0
  - libsodium=1.0.20=h99b78c6_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.8=h4a912ad_0
  - llvm-tools=19.1.7=hd2aecb6_1
  - llvm-tools-19=19.1.7=h87a4c7e_1
  - macosx_deployment_target_osx-arm64=11.0=h6553868_5
  - make=4.4.1=hc9fafa5_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.14.1=py311h5fbe615_0
  - openblas=0.3.30=openmp_hea878ba_3
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h3f644e9_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py311haa24f5a_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py311h5a8c52c_1
  - readline=8.3=h0b18652_0
  - sdkroot_env_osx-arm64=26.0=hc6f8731_5
  - setuptools=80.9.0=py311hca03da5_0
  - sigtool-codesign=0.1.3=h98dc951_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.1=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - stanio=0.5.1=pyhd8ed1ab_1
  - tapi=1600.0.11.8=h997e182_0
  - tbb=2022.3.0=h66ce52b_1
  - tbb-devel=2022.3.0=h41f9aa9_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.4=py311haa24f5a_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.20.3
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - llvmlite==0.46.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.6.1
      - numba==0.63.1
      - numpy==2.3.0
      - pillow==12.1.0
      - pyparsing==3.3.2
      - seaborn==0.13.2
      - sympy==1.14.0
      - torch==2.9.1
      - torchvision==0.24.1
      - xarray==2025.12.0
prefix: /opt/anaconda3/envs/stan311
